### ISSUE TITLE
How do I uninstall the desktop client?

### ISSUE THREAD

**Issue by aryan-shetty** [Qiqis-Notebook/qnb-client#5]
Hi, this is not exactly an issue but I can't find a way to uninstall the client so I'm opening this. I no longer want to use the desktop client so wanted to uninstall it.

**Comment by Kennie-L** [comment]
Apologies for the late response, the application is installed into the Windows App list and can be uninstalled there.
You can find it in Windows Settings > Apps > Installed apps, or search "Add or remove programs" into the windows search bar

**Comment by aryan-shetty** [comment]
No worries, and thanks. Not sure why I didn't think of that!
