### ISSUE TITLE
Loading time

### ISSUE THREAD

**Issue by flysand7** [Qiqis-Notebook/qnb-client#9]
With icons being at most 30-100 pixels wide it doesn't make sense that they're taking almost a minute to load. My internet usually at 2-5 mpbs.

**Comment by flysand7** [comment]
I also pressed "next" too many times, it took a lot of time for the map to load (1-2 minutes), despite me looking at the same route previously.

**Comment by Kennie-L** [comment]
Unfortunately this sounds like an ISP or CDN issue in your area or region, you can check this by using routes on your browser instead and you will most likely encounter similar loading times. Our assets are in the kilobytes and most of the time you'll only load a few megabytes worth of data. This is not a technical issue on our end that we can fix as we're configured to deliver our assets globally through our CDN provider.
